### ISSUE TITLE
Test gives weird result

### ISSUE THREAD

**Issue by Grantim** [huxingyi/simpleboolean#2]
Hello!

I tried to use this library for uniting two quite big objects, and got weird result.
I runned test project with attached files.
There were a lot of "Ignore triangle" lines in log.

Can you take a look, please

[models.zip](https://github.com/huxingyi/simpleboolean/files/4529045/models.zip)

**Comment by huxingyi** [comment]
Sorry, I no longer work on this project any more. Recommend using CGAL instead: CGAL::Polygon_mesh_processing::corefine_and_compute_union
